### ISSUE TITLE
Test in ResourceAdapterIT.java fails

### ISSUE THREAD

**Issue by nicenemo** [scheuchzer/outbound-connector#1]
Hi a Test on Date failes runnining on Windows 10 with Glashfish 4 and jdk 8.x. The expected datetimestring is set to a language locale version, e.g. Dutch. the actual value is English.

Quick fix, works for me but probably not enough:

I added Locale.ENGLISH to the SimpleDateFormatConstructor.

```
String expectedTime = 
new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy",Locale.ENGLISH).format(new Date());
```

[dateproblem.patch.zip](https://github.com/scheuchzer/outbound-connector/files/252089/dateproblem.patch.zip)

**Comment by scheuchzer** [comment]
Strange. Works on Ubuntu with Java 8 as it is. I added your patch. Thanks a lot!
